### ISSUE TITLE
Display guidepost names

### ISSUE THREAD

**Issue by Binnette** [RefugesInfo/mri#1]
Hi @sletuffe,

Can you please consider adding the guidepost names on your rendering?

Actually, only the elevation is displayed. What can be great is to display the name (if it exist) and the elevation (if it exist).

Here is how it is done on the default OSM rendering:
![image](https://user-images.githubusercontent.com/6597721/204161993-7dc375e5-c7a7-4ccd-bcd3-975d61fe8467.png)

The guidepost (icon + name + elevation) are displayed but only on zoom >= 19

Since mri is focused on outdoor activities, I think it should display those info on zoom >= 17

Have a nice day and TY for this awesome rendering :+1:

**Comment by sletuffe** [comment]
Hi Binnette,

Up until now, I have decided against showing guidepost's "names". My reasonning is that in most cases I know of, that isn't the name of the guidepost but the name of a nearby feature, just like it is in your case : "la croix de chamrousse" is allready displayed as a moutain peak to the West. And that is its true position.

By doing so, I'm in for a little act of militantism in order to encourage the tagging of ground features, and not only guideposts.

A little more debate can be read here : https://wiki.openstreetmap.org/wiki/Talk:Tag:information%3Dguidepost

And yeah, I know my choice is questionnable, and I can't say I'm not enclined to change the rendering one day... but not yet !

**Comment by Binnette** [comment]
Hi @sletuffe, I took a very well know place for my first example. But let's look on a random place.

Here is a screenshot of mri on last level of zoom:
[![2022-11-28-23-03-32-maps-refuges-info-Hiking-rendering-Mozilla-Firefox.png](https://i.postimg.cc/XXMXY5wY/2022-11-28-23-03-32-maps-refuges-info-Hiking-rendering-Mozilla-Firefox.png)](https://postimg.cc/tn59rYSK)

The same place with Waymarked Trails Hiking rendering:
[![2022-11-28-23-13-27-Waymarked-Trails-Hiking-Mozilla-Firefox.png](https://i.postimg.cc/RZ295mLv/2022-11-28-23-13-27-Waymarked-Trails-Hiking-Mozilla-Firefox.png)](https://postimg.cc/qNcWy9FF)

At the same zoom, I can have the name of the guidepost. So I can plan easily my hikes.

I created this bug because I was reading a hiking book that give "textual route" only by giving the names of guideposts. So I tried to plan a route with Brouter web and mri rendering. But sadly guidepost names are not shown on mri rendering 😢 

I am sure that adding guidepost names **ONLY at the very latest zoom** will not make your rendering not readable 👍 Plus it will make your rendering even more usable 🎉 

But please, add guidepost names only for the last zoom level, otherwise it can be not very readable (Waymarked trail)...
[![2022-11-28-22-54-57-Waymarked-Trails-Hiking-Mozilla-Firefox.png](https://i.postimg.cc/LsyWK3pL/2022-11-28-22-54-57-Waymarked-Trails-Hiking-Mozilla-Firefox.png)](https://postimg.cc/qt3w2ngv)

Please reconsider adding guidepost name but only on **last zoom level** 🙏 
Have a nice day 😇

**Comment by Binnette** [comment]
Hello @sletuffe, any remarks about my second message☝️? Have a nice day.

**Comment by sletuffe** [comment]
hello,

As said previously, I'm not willing to do it yet. And that is not for readability reasons.

**Comment by Binnette** [comment]
Hi @sletuffe, thank you for your answer. I hope that maybe later you will consider adding guideposts name at the very maximum level of zoom. Until then thank you for this excellent rendering that you offer (and maintain) for free 😊👌 Have a nice day
