### ISSUE TITLE
Display parking lots

### ISSUE THREAD

**Issue by Binnette** [RefugesInfo/mri#2]
Hi @sletuffe, I think you should display parkings lots on your rendering.

I'm using your rendering to plan my hikes on BRouter, but I really miss the parking lots to know where I can park my car to start my hikes. So I need to switch from your rendering to another one, each time I want to find a parking lot.

Can you please consider showing the parking lots? :pray: 

![image](https://user-images.githubusercontent.com/6597721/222954684-7f32a4d4-61bf-424c-a5cc-e61051f847d6.png)
mri // OSM

Have a nice day :+1:

**Comment by sletuffe** [comment]
hi,

Indeed, parking icons where not shown for parking tagged as area. I have corrected it.
example here :
https://maps.refuges.info/?zoom=16&lat=45.64405&lon=6.06085&layers=B0

However already generated tiles will stay as is, until next regeneration (and that could be in some months)

**Comment by Binnette** [comment]
Great! Thank @sletuffe :+1:
