### ISSUE TITLE
Add to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [RefugesInfo/mri#3]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add your project to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

**Comment by sletuffe** [comment]
Hi,

I have no objections being listed.
However, I had a quick look but it seams to be quite some work listing all tags in use in the mapnik xml files !

If anyone has the courage of creating a taginfo.json for this project, I'll accept it without problems, but I don't feel the need to spend that time for now.
Sorry.

**Comment by danieldegroot2** [comment]
Sure, thanks for the reply :-)
